name: 'Setup Defold bob.jar'
description: 'Sets up a specific version of bob.jar and dmengine_headless and adds them to PATH'
inputs:
  sha1:
    description: 'Engine hash or release channel ("stable", "beta", "alpha")'
    required: false
    default: 'stable'
  path:
    description: 'Path where to download the files'
    required: false
    default: '.defold'
outputs:
  sha1:
    description: 'Resolved engine hash'
  version:
    description: 'Resolved engine version'
  path:
    description: 'Absolute path to the downloaded files'
  bob:
    description: 'Absolute path to bob.jar'
  dmengine:
    description: 'Absolute path to dmengine_headless'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'play'
  color: 'blue'