name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: './'
      id: setup_defold
      with:
        path: .defold2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - env:
        BOB_VERSION: ${{ steps.setup_defold.outputs.version }}
        BOB_SHA1: ${{ steps.setup_defold.outputs.sha1 }}
        DEFOLD_PATH: ${{ steps.setup_defold.outputs.path }}
      run: |
        echo $BOB_VERSION $BOB_SHA1 > versions
        cat versions
        echo "Bob installed in: $BOB"
        java -jar $BOB --version | tee bob_versions && \
        cat bob_versions | sed 's/.*version: \([^ ]*\).*sha1: \([^ ]*\).*/\1 \2/' | cmp - versions && \
        test -x "$DEFOLD_PATH/dmengine_headless"